// gui/src/app/views/main-map/main-map.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import * as _ from 'lodash';
import * as ol from 'openlayers';
import {MapService} from "../../lib/map/map.service";
import {Subscription} from "rxjs";
import {RxUtils} from "../../lib/utils/RxUtils";
import {IProject} from "abcmap-shared";
import {IMainState} from "../../store";
import {Store} from "@ngrx/store";
import {LoggerFactory} from "../../lib/LoggerFactory";

@Component({
  selector: 'abc-main-map',
  templateUrl: './main-map.component.html',
  styleUrls: ['./main-map.component.scss']
})
export class MainMapComponent implements OnInit, OnDestroy {

  private logger = LoggerFactory.new("MainMapComponent");

  map?: ol.Map;
  project$?: Subscription;

  constructor(private mapService: MapService,
              private store: Store<IMainState>) {
  }

  ngOnInit() {
    this.setupMap();
    this.listenProject();
  }

  ngOnDestroy() {
    RxUtils.unsubscribe(this.project$);
  }

  listenProject() {
    this.store.subscribe(state => console.log(state));

    this.project$ = this.store
      .select(state => state.project)
      .subscribe(state => this.updateLayers(state.project))
  }

  updateLayers(project?: IProject) {
    if (!this.map || !project) {
      return;
    }
    this.logger.info("Updating layers ...");

    const _map = this.map;
    const olLayers = this.mapService.generateLayersFromProject(project);

    console.log(olLayers);

    // TODO: remove/add only if layers change
    _map.getLayers().forEach(lay => _map.removeLayer(lay));
    _.forEach(olLayers, lay => _map.addLayer(lay));
  }

  setupMap() {
    this.map = new ol.Map({
      target: 'main-openlayers-map',
      layers: [],
      view: new ol.View({
        center: ol.proj.fromLonLat([37.41, 8.82]),
        zoom: 4,
      }),
    });
  }

}

<div id="main-openlayers-map"></div>

// gui/src/views/MainMap.vue
<template>
    <div class="main-map-wrapper">
        <div id="openlayers-map"></div>
        <div style="display: none">{{ project }}</div>
    </div>
</template>

<script lang="ts">
import * as ol from 'openlayers';
import * as _ from 'lodash';
import {Component} from 'vue-property-decorator';
import {AbcExtendedVue} from '@/lib/utils/AbcExtendedVue';
import {IProject} from "../../../shared/dist";

@Component({
    components: {},
})
export default class MainMap extends AbcExtendedVue {

    public map?: ol.Map;

    mounted() {
        this.setupMap();
    }

    updated() {
        if(!this.map || !this.project){
            return;
        }
        const _map = this.map;
        const olLayers = this.abcServices.map.generateLayersFromProject(this.project);

        // TODO: remove/add only diff
        _map.getLayers().forEach(lay => _map.removeLayer(lay));
        _.forEach(olLayers, lay => _map.addLayer(lay));
    }

    setupMap() {
        this.map = new ol.Map({
            target: 'openlayers-map',
            layers: [],
            view: new ol.View({
                center: ol.proj.fromLonLat([37.41, 8.82]),
                zoom: 4,
            }),
        });
    }

    get project(): IProject | null {
        return this.abcStorew.project.getCurrentProject();
    }

}
</script>

<style lang="scss">

    #openlayers-map {
        position: absolute;
        width: 100%;
        height: 94%;
    }

</style>
