// gui/src/views/MainMap.vue
<template>
    <div class="main-map-wrapper">
        <div id="openlayers-map"></div>
    </div>
</template>

<script lang="ts">
    import * as ol from 'openlayers';
    import {Component, Vue} from 'vue-property-decorator';

    @Component({
        components: {},
    })
    export default class MainMap extends Vue {

        private map?: ol.Map;

        mounted() {
            this.map = new ol.Map({
                target: 'openlayers-map',
                layers: [
                    new ol.layer.Tile({
                        source: new ol.source.OSM()
                    })
                ],
                view: new ol.View({
                    center: ol.proj.fromLonLat([37.41, 8.82]),
                    zoom: 4
                })
            });
        }

    }
</script>

<style lang="scss">

    #openlayers-map {
        position: absolute;
        width: 100%;
        height: 94%;
    }

</style>

// packages/frontend/src/views/home/map/MainMap.tsx
import React, { Component, ReactNode } from 'react';
import { Map } from 'ol';
import { OSM } from 'ol/source';
import { fromLonLat } from 'ol/proj';
import View from 'ol/View';
import TileLayer from 'ol/layer/Tile';

interface State {
  map?: Map;
}

class MainMap extends Component<{}, State> {
  constructor(props: {}) {
    super(props);
    this.state = {};
  }

  public render(): ReactNode {
    return <div className="map" id="map"></div>;
  }

  public componentDidMount() {
    const map = new Map({
      target: 'map',
      layers: [
        new TileLayer({
          source: new OSM(),
        }),
      ],
      view: new View({
        center: fromLonLat([37.41, 8.82]),
        zoom: 4,
      }),
    });

    this.setState({ map });
  }

  public componentWillUnmount() {
    this.state.map?.dispose();
  }
}

export default MainMap;
